import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
const dir='/home/stickai/.openclaw/workspace/sharedspace/runtime-kernel-validation/ge2/ge2_r4_authoritative_rpc_command_list_builder_bridge';
fs.mkdirSync(dir,{recursive:true});
function sha(file){return fs.existsSync(file)?crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'):null}
function readJson(file){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch(e){return {parseError:String(e?.message||e)}}}
function run(args, timeout=120000){try{return {ok:true,status:0,stdout:execFileSync('openclaw',args,{cwd:'/home/stickai/.openclaw/workspace',encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout})}}catch(e){return{ok:false,status:e.status??null,stdout:e.stdout?.toString?.()??'',stderr:e.stderr?.toString?.()??String(e.message||e)}}}
const status=run(['gateway','status'],120000); fs.writeFileSync(path.join(dir,'gateway_status_final.txt'),status.stdout||status.stderr||'');
const plugins=run(['plugins','list','--json'],120000); fs.writeFileSync(path.join(dir,'plugins_list_final.json'),plugins.stdout||plugins.stderr||'');
const commandsSummary=readJson(path.join(dir,'commands_list_after_restart_summary.json'));
const pluginParsed=(()=>{try{return JSON.parse(plugins.stdout)}catch{return null}})();
const pluginList=Array.isArray(pluginParsed)?pluginParsed:(pluginParsed?.plugins||[]);
const ge2Plugin=pluginList.find(p=>p.id==='ge2-command')||null;
const surfaceResults=Array.isArray(commandsSummary.results)?commandsSummary.results:[];
const allGe2Present=surfaceResults.length>0&&surfaceResults.every(r=>r.ge2Present===true);
const allFakeAbsent=surfaceResults.length>0&&surfaceResults.every(r=>r.fakePresent===false);
const allCorePluginNamesPreserved=surfaceResults.length>0&&surfaceResults.every(r=>['pair','dreaming','phone','voice'].every(n=>(r.pluginNames||[]).includes(n)));
const statusPid=/pid (\d+)/.exec(status.stdout||'')?.[1]??null;
const serverMethods='/home/stickai/.npm-global/lib/node_modules/openclaw/dist/server-methods-Dw6hzI_j.js';
const serverText=fs.readFileSync(serverMethods,'utf8');
const markers={collectActiveRegistryPluginCommandEntries:serverText.includes('collectActiveRegistryPluginCommandEntries'), bridgeCall:serverText.includes('entries.push(...collectActiveRegistryPluginCommandEntries(params, entries))'), hiddenFilters:serverText.includes('command.hidden === true')&&serverText.includes('command.internal === true')&&serverText.includes('command.private === true')&&serverText.includes('command.exposeInCommandsList === false')};
const files={serverMethods, commands:'/home/stickai/.npm-global/lib/node_modules/openclaw/dist/commands-D2qp4St4.js', types:'/home/stickai/.npm-global/lib/node_modules/openclaw/dist/types-CdFhLeaX.js', preRepairSnapshot:path.join(dir,'pre_repair_snapshot.json'), localPatchValidation:path.join(dir,'local_patch_validation.json'), restartHold:path.join(dir,'restart_hold_20260630T0654Z.json'), commandParser:path.join(dir,'parse_live_commands_after_restart_20260630.mjs'), commandSummary:path.join(dir,'commands_list_after_restart_summary.json')};
const final={generatedAt:new Date().toISOString(), classification:'GE2_R4_BLOCKED_AUTHORITATIVE_BUILDER_BRIDGE_DID_NOT_EXPOSE_GE2', pass:false, passCriterion:'live Gateway RPC commands.list exposes /ge2', gateway:{previousPidBeforeRestart:'297423', finalPid:statusPid, healthOk:/Connectivity probe: ok/.test(status.stdout||''), adminCapable:/Capability: admin-capable/.test(status.stdout||''), statusExit:status.status}, patch:{file:serverMethods, sha256:sha(serverMethods), markers, shape:'Generic buildPluginCommandEntries bridge from active plugin registry commands; loaded plugin only; valid name/description; hidden/internal/private/no-list filters; provider restriction; de-dupe; no /ge2 hardcode.'}, commandSurfaces:{surfaceResults, allGe2Present, allFakeAbsent, allCorePluginNamesPreserved}, pluginManager:{ge2Loaded:ge2Plugin?.status==='loaded', ge2Commands:ge2Plugin?.commands||[], source:ge2Plugin?.source||null, contradiction:'plugin manager reports ge2-command loaded with commands:[ge2], but live commands.list surfaces omit /ge2 even after server-methods builder bridge.'}, negativeChecks:{fakeAbsent:allFakeAbsent, unrelatedPluginCommandsPreserved:allCorePluginNamesPreserved}, executionSurface:{attempted:false, reason:'Not attempted as success evidence because commands.list hard gate failed and user-facing /ge2 invocation could have side effects.'}, nextRecommendedScope:'R4 proves buildPluginCommandEntries bridge did not see active plugin registry commands in live RPC. Next diagnostic should instrument server-methods live builder to emit active registry command count/plugin ids to a private artifact/log, or identify an alternate commands.list implementation/bundle chunk actually serving the RPC. Do not continue with blind registry bridges.', noCronCloseoutApply:true, noPassClaim:true, files:Object.fromEntries(Object.entries(files).map(([k,v])=>[k,{path:v,exists:fs.existsSync(v),sha256:sha(v)}]))};
fs.writeFileSync(path.join(dir,'final_blocked_summary.json'),JSON.stringify(final,null,2)+'\n');
const md=`# GE2-R4 Final Classification\n\nClassification: \`${final.classification}\`\n\nPASS: **NO**\n\nHard gate: live Gateway RPC \`commands.list\` must expose \`/ge2\`. It did not.\n\n## Evidence\n\n- Gateway PID: \`${statusPid}\`; health/admin: ${final.gateway.healthOk&&final.gateway.adminCapable?'PASS':'FAIL'}\n- Patch markers present: ${JSON.stringify(markers)}\n- Live command surfaces: ${surfaceResults.map(r=>`${r.name}: count=${r.count}, ge2Present=${r.ge2Present}, fakePresent=${r.fakePresent}, pluginNames=${(r.pluginNames||[]).join(',')}`).join('; ')}\n- Plugin manager: ge2-command status=\`${ge2Plugin?.status||'missing'}\`, commands=${JSON.stringify(ge2Plugin?.commands||[])}\n- Negative checks: fake absent=${allFakeAbsent}; pair/dreaming/phone/voice preserved=${allCorePluginNamesPreserved}\n\n## Conclusion\n\nThe authoritative builder patch loaded on disk and Gateway restarted cleanly, but live \`commands.list\` still returned only the four existing plugin command entries. R4 remains blocked. Do not retry cron closeout apply.\n\n## Next diagnostic\n\nInstrument the live \`server-methods\` builder path itself to prove whether it sees \`getActivePluginRegistry()?.commands\`; if it does not, identify the alternate live registry or alternate bundle chunk serving \`commands.list\`. Stop blind registry/singleton bridges.\n`;
fs.writeFileSync(path.join(dir,'GE2_R4_FINAL_BLOCKED.md'),md);
const manifest=[]; for(const [name,meta] of Object.entries(final.files)) manifest.push({name,path:meta.path,exists:meta.exists,sha256:meta.sha256});
manifest.push({name:'final_blocked_summary',path:path.join(dir,'final_blocked_summary.json'),exists:true,sha256:sha(path.join(dir,'final_blocked_summary.json'))});
manifest.push({name:'final_markdown',path:path.join(dir,'GE2_R4_FINAL_BLOCKED.md'),exists:true,sha256:sha(path.join(dir,'GE2_R4_FINAL_BLOCKED.md'))});
manifest.push({name:'gateway_status_final',path:path.join(dir,'gateway_status_final.txt'),exists:true,sha256:sha(path.join(dir,'gateway_status_final.txt'))});
manifest.push({name:'plugins_list_final',path:path.join(dir,'plugins_list_final.json'),exists:true,sha256:sha(path.join(dir,'plugins_list_final.json'))});
fs.writeFileSync(path.join(dir,'final_file_manifest_20260630.json'),JSON.stringify({generatedAt:new Date().toISOString(),allExist:manifest.every(x=>x.exists),count:manifest.length,manifest},null,2)+'\n');
console.log(JSON.stringify({classification:final.classification,pass:false,finalPid:statusPid,healthOk:final.gateway.healthOk,adminCapable:final.gateway.adminCapable,patchMarkers:markers,surfaceResults:surfaceResults.map(r=>({name:r.name,count:r.count,ge2Present:r.ge2Present,fakePresent:r.fakePresent,pluginNames:r.pluginNames})),ge2Plugin:{status:ge2Plugin?.status,commands:ge2Plugin?.commands,source:ge2Plugin?.source},manifestAllExist:manifest.every(x=>x.exists)},null,2));
